export default function() {
    let mdheroxxs = [{
            num: 0,
            name: "琴",
            sex: "女",
            city: "蒙德",
            starts: 5,
            element: "风",
            arms: "单手剑",
        },
        {
            num: 1,
            name: "安柏",
            sex: "女",
            city: "蒙德",
            starts: 4,
            element: "火",
            arms: "弓",
        },
        {
            num: 2,
            name: "丽莎",
            sex: "女",
            city: "蒙德",
            starts: 4,
            element: "雷",
            arms: "法器",
        },
        {
            num: 3,
            name: "凯亚",
            sex: "男",
            city: "蒙德",
            starts: 4,
            element: "冰",
            arms: "单手剑",
        },
        {
            num: 4,
            name: "芭芭拉",
            sex: "女",
            city: "蒙德",
            starts: 4,
            element: "水",
            arms: "法器",
        },
        {
            num: 5,
            name: "迪卢克",
            sex: "男",
            city: "蒙德",
            starts: 5,
            element: "火",
            arms: "双手剑",
        },
        {
            num: 6,
            name: "雷泽",
            sex: "男",
            city: "蒙德",
            starts: 4,
            element: "雷",
            arms: "双手剑",
        },
        {
            num: 7,
            name: "温迪",
            sex: "男",
            city: "蒙德",
            starts: 5,
            element: "风",
            arms: "弓",
        },
        {
            num: 8,
            name: "可莉",
            sex: "女",
            city: "蒙德",
            starts: 5,
            element: "火",
            arms: "法器",
        },
    ];
    return mdheroxxs;
}